import Foundation
import AppKit
import Testing
@testable import PSTranscribe

@MainActor
@Suite("Phase 18.1 D-19 -- dictation when zero destinations enabled", .serialized)
struct DictationZeroDestinationsTests {

    private func freshSettings() -> AppSettings {
        let keys = ["localFileEnabled", "localFileRoot", "obsidianEnabled",
                    "obsidianFolderPath", "notionAutoSendEnabled", "notionDatabaseID"]
        for k in keys { UserDefaults.standard.removeObject(forKey: k) }
        let s = AppSettings()
        s.localFileEnabled = false
        s.obsidianEnabled = false
        s.notionAutoSendEnabled = false
        return s
    }

    @Test("clipboard fires + library entry stores inlineTranscript when all destinations off")
    func zeroDestinations_clipboardFiresInlineStored() async {
        await PasteboardTestLock.shared.acquire()
        defer { Task { await PasteboardTestLock.shared.release() } }
        defer { NSPasteboard.general.clearContents() }

        let settings = freshSettings()
        defer {
            for k in ["localFileEnabled", "localFileRoot", "obsidianEnabled",
                      "obsidianFolderPath", "notionAutoSendEnabled", "notionDatabaseID"] {
                UserDefaults.standard.removeObject(forKey: k)
            }
        }

        let library = LibraryStore()
        let sessionCoord = SessionCoordinator()
        let saveDest = SaveDestinations(settings: settings, notionService: NotionService())
        let coordinator = DictationCoordinator(
            settings: settings,
            sessionCoordinator: sessionCoord,
            libraryStore: library,
            saveDestinations: saveDest
        )
        sessionCoord.dictation = coordinator

        // LibraryStore loads existing entries from disk on init. Snapshot the initial
        // count so we can assert the new entry was added without depending on a clean library.
        let entriesBefore = await library.entries.count

        let assembled = "this is the dictation body \(UUID().uuidString)"
        coordinator._test_setState(.listening)
        coordinator._test_setSessionStartTime(Date())
        coordinator._test_setElapsed(5)
        coordinator.dictationStore.volatileYouText = assembled

        await coordinator.endDictation()
        try? await Task.sleep(for: .milliseconds(50))

        // 1. Clipboard contains assembled transcript (D-15 unconditional clipboard).
        let pbString = NSPasteboard.general.string(forType: .string)
        #expect(pbString == assembled, "DICT-05: clipboard write is unconditional even with zero destinations")

        // 2. Library entry has inlineTranscript and empty filePath (D-19).
        // LibraryStore.addEntry inserts at index 0 (newest first), so the new entry
        // is at entries[0].
        let entries = await library.entries
        #expect(entries.count == entriesBefore + 1, "exactly one new library entry added")
        guard let stored = entries.first(where: { $0.inlineTranscript == assembled }) else {
            Issue.record("could not locate the new dictation entry by inlineTranscript match")
            return
        }
        #expect(stored.inlineTranscript == assembled, "D-19: inline transcript stored when no file written")
        #expect(stored.filePath == "", "D-19: no file path when all destinations disabled")

        // Cleanup the test entry so we don't accumulate state on disk.
        await library.removeEntry(id: stored.id)

        // 3. Privacy markers were applied (DICT-09).
        let pbItems = NSPasteboard.general.pasteboardItems ?? []
        let hasTransient = pbItems.contains { item in
            item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        }
        let hasAutoGen = pbItems.contains { item in
            item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        }
        #expect(hasTransient, "DICT-09: TransientType marker present")
        #expect(hasAutoGen, "DICT-09: AutoGeneratedType marker present")
    }

    @Test("isAnyDestinationEnabled is false when all three off")
    func saveDestinationsReportsNoneEnabled() {
        let settings = freshSettings()
        defer {
            for k in ["localFileEnabled", "obsidianEnabled", "notionAutoSendEnabled"] {
                UserDefaults.standard.removeObject(forKey: k)
            }
        }
        let saveDest = SaveDestinations(settings: settings, notionService: NotionService())
        #expect(saveDest.isAnyDestinationEnabled == false)
    }
}
