// AUTO-GENERATED by scripts/build-sidebar-data.mjs. Do not edit by hand.
// Source: each src/app/docs/*\/page.mdx's `export const doc`. Regenerate via `pnpm predev` or `pnpm prebuild`.

export type DiscoveredDoc = { slug: string; href: string; navTitle: string; group: string; order: number }

export const DISCOVERED_DOCS: DiscoveredDoc[] = [
  {
    "slug": "configuring-your-vault",
    "href": "/docs/configuring-your-vault",
    "navTitle": "Configuring your vault",
    "group": "Start here",
    "order": 2
  },
  {
    "slug": "notion-property-mapping",
    "href": "/docs/notion-property-mapping",
    "navTitle": "Notion property mapping",
    "group": "Reference",
    "order": 2
  }
]
