// AUTO-GENERATED by scripts/build-sidebar-data.mjs. Do not edit by hand.
// Source: each src/app/docs/*\/page.mdx's `export const doc`. Regenerate via `pnpm predev` or `pnpm prebuild`.

export type DiscoveredDoc = { slug: string; href: string; navTitle: string; group: string; order: number }

export const DISCOVERED_DOCS: DiscoveredDoc[] = [
  {
    "slug": "getting-started",
    "href": "/docs/getting-started",
    "navTitle": "Getting started",
    "group": "Start here",
    "order": 1
  },
  {
    "slug": "keyboard-shortcuts",
    "href": "/docs/keyboard-shortcuts",
    "navTitle": "Keyboard shortcuts",
    "group": "Reference",
    "order": 1
  }
]
