import Testing
import Foundation
import AppKit
@testable import PSTranscribe

/// `.serialized` because all 3 tests share NSPasteboard.general (system-global state).
@Suite("ClipboardPrivacyMarkersTests", .serialized)
struct ClipboardPrivacyMarkersTests {

    @MainActor
    private func makeCoordinator() -> DictationCoordinator {
        let settings = AppSettings()
        settings.dictationOutputMode = .clipboard
        let coordinator = SessionCoordinator()
        let library = LibraryStore()
        return DictationCoordinator(settings: settings, sessionCoordinator: coordinator, libraryStore: library)
    }

    @Test @MainActor func transientTypeMarkerSetAfterClipboardWrite() async {
        await PasteboardTestLock.shared.acquire()
        defer { Task { await PasteboardTestLock.shared.release() } }
        defer { NSPasteboard.general.clearContents() }
        let dict = makeCoordinator()
        dict._test_writeToClipboard("hello world")
        #expect(NSPasteboard.general.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) != nil)
    }

    @Test @MainActor func autoGeneratedTypeMarkerSetAfterClipboardWrite() async {
        await PasteboardTestLock.shared.acquire()
        defer { Task { await PasteboardTestLock.shared.release() } }
        defer { NSPasteboard.general.clearContents() }
        let dict = makeCoordinator()
        dict._test_writeToClipboard("hello world")
        #expect(NSPasteboard.general.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) != nil)
    }

    @Test @MainActor func clipboardStringEqualsAssembledTranscript() async {
        await PasteboardTestLock.shared.acquire()
        defer { Task { await PasteboardTestLock.shared.release() } }
        defer { NSPasteboard.general.clearContents() }
        let dict = makeCoordinator()
        dict._test_writeToClipboard("the quick brown fox")
        #expect(NSPasteboard.general.string(forType: .string) == "the quick brown fox")
    }
}
