import Testing
import Foundation
import AppKit
@testable import PSTranscribe

@Suite("ClipboardPrivacyMarkersTests")
struct ClipboardPrivacyMarkersTests {

    @Test(.disabled("Pending Plan 18-06 -- TransientType marker present"))
    @MainActor func transientTypeMarkerSetAfterClipboardWrite() async {
        // After endDictation with mode==.clipboard:
        // NSPasteboard.general.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) != nil
        #expect(Bool(true))
    }

    @Test(.disabled("Pending Plan 18-06 -- AutoGeneratedType marker present"))
    @MainActor func autoGeneratedTypeMarkerSetAfterClipboardWrite() async {
        // NSPasteboard.general.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) != nil
        #expect(Bool(true))
    }

    @Test(.disabled("Pending Plan 18-06 -- assembled transcript matches utterances + volatile"))
    @MainActor func clipboardStringEqualsAssembledTranscript() async {
        // utterances=["hello world","foo bar"], volatileYouText="baz"
        // pasteboard.string(.string) == "hello world foo bar baz"
        #expect(Bool(true))
    }
}
